name: Publish Images

on:
  release:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: bullseye
          - variant: alpine
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kiritaniayaka/pg_jieba
          tags: |
            type=raw,value=${{ matrix.variant }}
            type=raw,value=latest,enable=${{ matrix.variant == 'bullseye' }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./15/${{ matrix.variant }}/Dockerfile
          platforms: linux/amd64,linux/arm64${{ (matrix.variant == 'alpine' && ',linux/arm/v7,linux/386') || '' }}
          push: false
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}
